"""drop the shopify product catalogue and sku matching

Revision ID: ebe4820b37fa
Revises: 53bd376b8df6
Created: 2026-07-30 10:08:42.577235
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ebe4820b37fa'
down_revision: str | None = '53bd376b8df6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_candidates_match_run_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_run_queue'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_sku'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_workspace_id'))

    op.drop_table('match_candidates')
    with op.batch_alter_table('match_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_match_runs_workspace_started'))

    op.drop_table('match_runs')
    with op.batch_alter_table('shopify_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_variants_product_id'))
        batch_op.drop_index(batch_op.f('ix_shopify_variants_sku_normalized'))
        batch_op.drop_index(batch_op.f('ix_shopify_variants_workspace_id'))

    op.drop_table('shopify_variants')
    with op.batch_alter_table('sku_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_links_variant'))
        batch_op.drop_index(batch_op.f('ix_sku_links_workspace_id'))

    op.drop_table('sku_links')
    with op.batch_alter_table('shopify_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopify_products_connection_id'))
        batch_op.drop_index(batch_op.f('ix_shopify_products_workspace_id'))

    op.drop_table('shopify_products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_products',
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.Column('connection_id', sa.INTEGER(), nullable=False),
    sa.Column('shopify_product_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('handle', sa.VARCHAR(length=255), nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vendor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('synced_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['shopify_connections.id'], name=op.f('fk_shopify_products_connection_id_shopify_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_shopify_products_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopify_products')),
    sa.UniqueConstraint('workspace_id', 'shopify_product_id', name=op.f('workspace_product'))
    )
    with op.batch_alter_table('shopify_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopify_products_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopify_products_connection_id'), ['connection_id'], unique=False)

    op.create_table('sku_links',
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.Column('sku_normalized', sa.VARCHAR(length=120), nullable=False),
    sa.Column('shopify_variant_id', sa.BIGINT(), nullable=True),
    sa.Column('variant_row_id', sa.INTEGER(), nullable=True),
    sa.Column('link_type', sa.VARCHAR(length=24), nullable=False),
    sa.Column('source', sa.VARCHAR(length=16), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('stale_reason', sa.VARCHAR(length=64), nullable=True),
    sa.Column('confidence_at_confirm', sa.INTEGER(), nullable=True),
    sa.Column('confirmed_by', sa.INTEGER(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_sku_links_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_row_id'], ['shopify_variants.id'], name=op.f('fk_sku_links_variant_row_id_shopify_variants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sku_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_links')),
    sa.UniqueConstraint('workspace_id', 'sku_normalized', name=op.f('workspace_sku_link'))
    )
    with op.batch_alter_table('sku_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_links_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_links_variant'), ['workspace_id', 'shopify_variant_id'], unique=False)

    op.create_table('shopify_variants',
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('shopify_variant_id', sa.BIGINT(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=120), nullable=True),
    sa.Column('sku_normalized', sa.VARCHAR(length=120), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('price_paise', sa.INTEGER(), nullable=True),
    sa.Column('inventory_quantity', sa.INTEGER(), nullable=True),
    sa.Column('synced_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['shopify_products.id'], name=op.f('fk_shopify_variants_product_id_shopify_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_shopify_variants_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopify_variants')),
    sa.UniqueConstraint('workspace_id', 'shopify_variant_id', name=op.f('workspace_variant'))
    )
    with op.batch_alter_table('shopify_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopify_variants_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopify_variants_sku_normalized'), ['workspace_id', 'sku_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopify_variants_product_id'), ['product_id'], unique=False)

    op.create_table('match_runs',
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=16), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('matched_count', sa.INTEGER(), nullable=False),
    sa.Column('review_count', sa.INTEGER(), nullable=False),
    sa.Column('missing_count', sa.INTEGER(), nullable=False),
    sa.Column('duplicate_count', sa.INTEGER(), nullable=False),
    sa.Column('auto_linked_count', sa.INTEGER(), nullable=False),
    sa.Column('skus_considered', sa.INTEGER(), nullable=False),
    sa.Column('progress_pct', sa.INTEGER(), nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=64), nullable=True),
    sa.Column('error_detail', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_match_runs_triggered_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_match_runs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_runs'))
    )
    with op.batch_alter_table('match_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_runs_workspace_started'), ['workspace_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('match_candidates',
    sa.Column('match_run_id', sa.INTEGER(), nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), nullable=False),
    sa.Column('sku_normalized', sa.VARCHAR(length=120), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=120), nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('quantity_on_hand', sa.INTEGER(), nullable=True),
    sa.Column('queue', sa.VARCHAR(length=16), nullable=False),
    sa.Column('shopify_variant_id', sa.BIGINT(), nullable=True),
    sa.Column('variant_sku', sa.VARCHAR(length=120), nullable=True),
    sa.Column('variant_title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('product_title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confidence', sa.INTEGER(), nullable=True),
    sa.Column('rule', sa.VARCHAR(length=16), nullable=True),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['match_run_id'], ['match_runs.id'], name=op.f('fk_match_candidates_match_run_id_match_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_match_candidates_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_candidates'))
    )
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_candidates_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_sku'), ['workspace_id', 'sku_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_run_queue'), ['match_run_id', 'queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_match_run_id'), ['match_run_id'], unique=False)

    # ### end Alembic commands ###
