"""sheet count and complaint columns

The fixed upload format: three count columns and ten complaint categories.
Existing rows predate them and default to zero — a sheet that did not report a
complaint reported no complaints.

Revision ID: 33d0bd196f2a
Revises: ebe4820b37fa
Created: 2026-07-30 10:38:45.822091
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '33d0bd196f2a'
down_revision: str | None = 'ebe4820b37fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_count", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("total_orders", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("total_qty", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("item_defect_partial", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("item_defect_complete", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("item_damage_partial", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("item_damage_complete", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("order_wrong_parcel", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("electronics_nonworking_partial", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("electronics_nonworking_complete", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("missing", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("missing_part", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("item_mismatch_wrong_item", sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('item_mismatch_wrong_item')
        batch_op.drop_column('missing_part')
        batch_op.drop_column('missing')
        batch_op.drop_column('electronics_nonworking_complete')
        batch_op.drop_column('electronics_nonworking_partial')
        batch_op.drop_column('order_wrong_parcel')
        batch_op.drop_column('item_damage_complete')
        batch_op.drop_column('item_damage_partial')
        batch_op.drop_column('item_defect_complete')
        batch_op.drop_column('item_defect_partial')
        batch_op.drop_column('total_qty')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('total_count')

    # ### end Alembic commands ###
